### ISSUE TITLE
how do i access the numbers on the counter?

### ISSUE THREAD

**Issue by DejiAwoniyi** [yasaricli/react-native-counters#13]
What prop do I use to access the actual value of the counter? So for example I want to console.log '5' when the counter reads 5

**Comment by DavWill19** [comment]
did you ever figure this out? I have the same question

**Comment by joshuachang2311** [comment]
Same question here

**Comment by nic-00** [comment]
Not sure is this what you're looking for, but i get the value by using this line

`onChange={value => console.log(value)}`

Hope it helps 😆
